---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install Apache on Debian-based systems
  apt:
    name: "{{ apache_packages }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Apache on RedHat-based systems
  yum:
    name: "{{ apache_packages }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Ensure Apache service is started and enabled
  systemd:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: Install PHP and required modules (Debian)
  apt:
    name:
      - php
      - php-mysql
      - php-curl
      - php-gd
      - php-mbstring
      - php-xml
      - php-zip
      - libapache2-mod-php
    state: present
  when: ansible_os_family == "Debian"
  notify: restart apache

- name: Install PHP and required modules (RedHat)
  yum:
    name:
      - php
      - php-mysqlnd
      - php-curl
      - php-gd
      - php-mbstring
      - php-xml
      - php-zip
    state: present
  when: ansible_os_family == "RedHat"
  notify: restart apache

- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy WordPress files to document root
  copy:
    src: /tmp/wordpress/
    dest: "{{ apache_document_root }}"
    remote_src: yes
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: '0755'

- name: Create WordPress config from template
  template:
    src: wp-config.php.j2
    dest: "{{ apache_document_root }}/wp-config.php"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: '0644'

- name: Set proper permissions on WordPress directory
  file:
    path: "{{ apache_document_root }}"
    state: directory
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    recurse: yes
