---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install MySQL on Debian-based systems
  apt:
    name: "{{ mysql_packages }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install MySQL on RedHat-based systems
  yum:
    name: "{{ mysql_packages }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Ensure MySQL service is started and enabled
  systemd:
    name: "{{ mysql_service }}"
    state: started
    enabled: yes

- name: Install Python MySQL library (Debian)
  apt:
    name: python3-pymysql
    state: present
  when: ansible_os_family == "Debian"

- name: Install Python MySQL library (RedHat)
  yum:
    name: python3-PyMySQL
    state: present
  when: ansible_os_family == "RedHat"

- name: Create WordPress database
  community.mysql.mysql_db:
    name: "{{ wordpress_db_name }}"
    state: present
    login_unix_socket: "{{ mysql_socket }}"
  ignore_errors: yes

- name: Create WordPress database user
  community.mysql.mysql_user:
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_password }}"
    priv: "{{ wordpress_db_name }}.*:ALL"
    state: present
    login_unix_socket: "{{ mysql_socket }}"
  ignore_errors: yes
